CREATE TABLE chapitre_01 (
id_cha1 SERIAL NOT NULL PRIMARY KEY, 
topo_theorique TEXT, 
donnees_cas TEXT, 
reponse_cas_qcm TEXT, 
synthese TEXT, 
avis_expert_rep_q1 TEXT, 
axes_reflex_rep_q1 TEXT, 
axes_reflex_rep_q2 TEXT,
partie_1 TEXT, 
categorie_a TEXT, 
souscategorie_1 TEXT, 
souscategorie_2 TEXT, 
souscategorie_3 TEXT, 
categorie_b TEXT, 
souscategorie_4 TEXT, 
souscategorie_5 TEXT, 
branche_1 TEXT, 
branche_2 TEXT,
partie_2 TEXT, 
categorie_c TEXT, 
souscategorie_6 TEXT, 
souscategorie_7 TEXT, 
categorie_d TEXT, 
souscategorie_8 TEXT, 
souscategorie_9 TEXT, 
conclusion TEXT
);

UPDATE chapitre_01 SET id_cha1= '1';

CREATE TABLE chapitre_02 (
id_cha2 SERIAL NOT NULL PRIMARY KEY, 
topo_theorique TEXT, 
donnees_cas TEXT, 
reponse_cas_qcm TEXT, 
synthese TEXT, 
avis_expert_rep_q1 TEXT, 
axes_reflex_rep_q1 TEXT,
partie_1 TEXT, 
categorie_a TEXT, 
souscategorie_1 TEXT, 
souscategorie_2 TEXT, 
souscategorie_3 TEXT, 
souscategorie_4 TEXT, 
souscategorie_5 TEXT, 
souscategorie_6 TEXT, 
souscategorie_7 TEXT,
branche_a TEXT, 
branche_b TEXT, 
branche_c TEXT, 
categorie_b TEXT, 
souscategorie_8 TEXT, 
souscategorie_9 TEXT, 
branche_d TEXT, 
sousbranche_1 TEXT, 
sousbranche_2 TEXT, 
sousbranche_3 TEXT, 
sousbranche_4 TEXT, 
sousbranche_5 TEXT,
sousbranche_6 TEXT,
partie_2 TEXT, 
categorie_c TEXT, 
souscategorie_10 TEXT, 
souscategorie_11 TEXT, 
souscategorie_12 TEXT, 
categorie_d TEXT, 
conclusion TEXT
);

UPDATE chapitre_02 SET id_cha2= '2';

CREATE TABLE chapitre_03 (
id_cha3 SERIAL NOT NULL PRIMARY KEY, 
topo_theorique TEXT, 
donnees_cas TEXT, 
reponse_cas_qcm TEXT, 
synthese TEXT, 
avis_expert_rep_q1 TEXT, 
axes_reflex_rep_q1 TEXT,
partie_1 TEXT, 
categorie_a TEXT, 
souscategorie_13 TEXT, 
branche_e TEXT, 
branche_f TEXT, 
branche_g TEXT, 
souscategorie_14 TEXT, 
branche_h TEXT, 
sousbranche_7 TEXT, 
sousbranche_8 TEXT, 
sousbranche_9 TEXT, 
souscategorie_15 TEXT, 
branche_i TEXT, 
branche_j TEXT, 
branche_k TEXT, 
branche_l TEXT, 
branche_m TEXT, 
categorie_b TEXT, 
souscategorie_1 TEXT, 
souscategorie_2 TEXT, 
souscategorie_3 TEXT, 
souscategorie_4 TEXT, 
souscategorie_5 TEXT, 
souscategorie_6 TEXT, 
souscategorie_7 TEXT, 
souscategorie_8 TEXT,
partie_2 TEXT, 
categorie_c TEXT, 
categorie_d TEXT, 
categorie_e TEXT, 
conclusion TEXT
);

UPDATE chapitre_03 SET id_cha3= '3';

CREATE TABLE chapitre_04 (
id_cha4 SERIAL NOT NULL PRIMARY KEY, 
topo_theorique TEXT, 
donnees_cas TEXT, 
reponse_cas_qcm TEXT, 
synthese TEXT, 
avis_expert TEXT, 
avis_expert_rep_q1 TEXT, 
axes_reflex_rep_q1 TEXT,
partie_1 TEXT, 
categorie_a TEXT, 
categorie_b TEXT, 
categorie_c TEXT, 
souscategorie_1 TEXT, 
souscategorie_2 TEXT, 
souscategorie_3 TEXT, 
souscategorie_4 TEXT,
partie_2 TEXT, 
categorie_d TEXT, 
categorie_e TEXT, 
souscategorie_5 TEXT, 
souscategorie_6 TEXT, 
souscategorie_7 TEXT, 
conclusion TEXT
);

UPDATE chapitre_04 SET id_cha4= '4';

CREATE TABLE chapitre_05 (
id_cha5 SERIAL NOT NULL PRIMARY KEY, 
topo_theorique TEXT, 
donnees_cas TEXT, 
reponse_cas_qcm TEXT, 
synthese TEXT, 
avis_expert TEXT, 
avis_expert_rep_q1 TEXT, 
avis_expert_rep_q2 TEXT, 
axes_reflex_rep_q1 TEXT, 
axes_reflex_rep_q2 TEXT,
partie_1 TEXT, 
categorie_a TEXT, 
categorie_b TEXT, 
souscategorie_1 TEXT, 
souscategorie_2 TEXT, 
souscategorie_3 TEXT, 
souscategorie_4 TEXT,
partie_2 TEXT, 
categorie_c TEXT, 
souscategorie_5 TEXT, 
souscategorie_6 TEXT, 
souscategorie_7 TEXT, 
categorie_d TEXT, 
souscategorie_8 TEXT, 
branche_a TEXT, 
sousbranche_1 TEXT, 
sousbranche_2 TEXT, 
sousbranche_3 TEXT, 
sousbranche_4 TEXT, 
sousbranche_5 TEXT, 
sousbranche_6 TEXT, 
branche_b TEXT, 
sousbranche_7 TEXT, 
sousbranche_8 TEXT, 
sousbranche_9 TEXT, 
souscategorie_9 TEXT, 
branche_c TEXT, 
branche_d TEXT, 
souscategorie_10 TEXT, 
conclusion TEXT
);

UPDATE chapitre_05 SET id_cha5= '5';

CREATE TABLE chapitre_06 (
id_cha6 SERIAL NOT NULL PRIMARY KEY, 
topo_theorique TEXT, 
donnees_cas TEXT, 
reponse_cas_qcm TEXT, 
synthese TEXT, 
avis_expert TEXT, 
avis_expert_rep_q1 TEXT, 
axes_reflex_rep_q1 TEXT, 
axes_reflex_rep_q2 TEXT,
partie_1 TEXT, 
categorie_a TEXT, 
souscategorie_1 TEXT, 
souscategorie_2 TEXT, 
categorie_b TEXT,
partie_2 TEXT, 
categorie_c TEXT, 
categorie_d TEXT, 
souscategorie_3 TEXT, 
souscategorie_4 TEXT, 
conclusion TEXT
);

UPDATE chapitre_06 SET id_cha6= '6';

CREATE TABLE chapitre_07 (
id_cha7 SERIAL NOT NULL PRIMARY KEY, 
topo_theorique TEXT, 
donnees_cas TEXT, 
reponse_cas_qcm TEXT, 
synthese TEXT, 
avis_expert TEXT, 
avis_expert_rep_q1 TEXT, 
avis_expert_rep_q2 TEXT, 
avis_expert_rep_q3 TEXT, 
axes_reflex_rep_q1 TEXT, 
axes_reflex_rep_q2 TEXT, 
axes_reflex_rep_q3 TEXT,
partie_1 TEXT, 
categorie_a TEXT, 
categorie_b TEXT,
partie_2 TEXT, 
categorie_c TEXT, 
souscategorie_1 TEXT, 
branche_a TEXT, 
branche_b TEXT, 
souscategorie_2 TEXT, 
branche_c TEXT, 
branche_d TEXT, 
categorie_d TEXT, 
souscategorie_3 TEXT, 
branche_e TEXT, 
branche_f TEXT, 
souscategorie_4 TEXT, 
branche_g TEXT, 
branche_h TEXT,
partie_3 TEXT, 
categorie_e TEXT, 
souscategorie_5 TEXT, 
souscategorie_6 TEXT, 
categorie_f TEXT, 
souscategorie_7 TEXT, 
souscategorie_8 TEXT, 
branche_i TEXT, 
branche_j TEXT, 
branche_k TEXT, 
conclusion TEXT
);

UPDATE chapitre_07 SET id_cha7= '7';

CREATE TABLE chapitre_08 (
id_cha8 SERIAL NOT NULL PRIMARY KEY, 
topo_theorique TEXT, 
donnees_cas TEXT, 
reponse_cas_qcm TEXT, 
synthese TEXT, 
avis_expert TEXT, 
avis_expert_rep_q1 TEXT, 
axes_reflex_rep_q1 TEXT,
partie_1 TEXT, 
categorie_a TEXT, 
categorie_b TEXT, 
categorie_c TEXT,
partie_2 TEXT, 
categorie_d TEXT, 
categorie_e TEXT, 
conclusion TEXT
);

UPDATE chapitre_08 SET id_cha8= '8';

CREATE TABLE chapitre_09 (
id_cha9 SERIAL NOT NULL PRIMARY KEY, 
topo_theorique TEXT, 
donnees_cas TEXT, 
reponse_cas_qcm TEXT, 
synthese TEXT, 
avis_expert TEXT, 
avis_expert_rep_q1 TEXT, 
axes_reflex_rep_q1 TEXT, 
axes_reflex_rep_q2 TEXT,
partie_1 TEXT, 
categorie_a TEXT, 
categorie_b TEXT,
partie_2 TEXT, 
categorie_c TEXT, 
categorie_d TEXT
);

UPDATE chapitre_09 SET id_cha9= '9';

CREATE TABLE chapitre_10 (
id_cha10 SERIAL NOT NULL PRIMARY KEY, 
topo_theorique TEXT, 
donnees_cas TEXT, 
reponse_cas_qcm TEXT, 
synthese TEXT, 
avis_expert TEXT, 
avis_expert_rep_q1 TEXT, 
avis_expert_rep_q2 TEXT, 
axes_reflex_rep_q1 TEXT, 
axes_reflex_rep_q2 TEXT,
partie_1 TEXT, 
categorie_a TEXT, 
categorie_b TEXT,
partie_2 TEXT, 
categorie_c TEXT, 
categorie_d TEXT, 
conclusion TEXT
);

UPDATE chapitre_10 SET id_cha10= '10';

CREATE TABLE chapitre_11 (
id_cha11 SERIAL NOT NULL PRIMARY KEY, 
topo_theorique TEXT, 
donnees_cas TEXT, 
reponse_cas_qcm TEXT, 
synthese TEXT, 
avis_expert TEXT, 
avis_expert_rep_q1 TEXT, 
avis_expert_rep_q2 TEXT, 
axes_reflex_rep_q1 TEXT, 
axes_reflex_rep_q2 TEXT, 
axes_reflex_rep_q3 TEXT,
partie_1 TEXT, 
categorie_a TEXT, 
categorie_b TEXT,
partie_2 TEXT, 
categorie_c TEXT, 
categorie_d TEXT, 
conclusion TEXT
);

UPDATE chapitre_11 SET id_cha11= '11';

CREATE TABLE chapitre_12 (
id_cha12 SERIAL NOT NULL PRIMARY KEY, 
topo_theorique TEXT, 
donnees_cas TEXT, 
reponse_cas_qcm TEXT, 
synthese TEXT, 
avis_expert TEXT, 
avis_expert_rep_q1 TEXT, 
avis_expert_rep_q2 TEXT, 
axes_reflex_rep_q1 TEXT,
partie_1 TEXT, 
categorie_a TEXT, 
categorie_b TEXT,
partie_2 TEXT, 
categorie_c TEXT, 
souscategorie_1 TEXT, 
souscategorie_2 TEXT, 
categorie_d TEXT, 
conclusion TEXT
);

UPDATE chapitre_12 SET id_cha12= '12';

CREATE TABLE chapitre_13 (
id_cha13 SERIAL NOT NULL PRIMARY KEY, 
topo_theorique TEXT, 
donnees_cas TEXT, 
reponse_cas_qcm TEXT, 
synthese TEXT, 
avis_expert TEXT, 
avis_expert_rep_q1 TEXT, 
avis_expert_rep_q2 TEXT, 
axes_reflex_rep_q1 TEXT, 
axes_reflex_rep_q2 TEXT,
partie_1 TEXT, 
categorie_a TEXT, 
souscategorie_1 TEXT, 
branche_a TEXT, 
branche_b TEXT, 
souscategorie_2 TEXT, 
souscategorie_3 TEXT, 
souscategorie_4 TEXT, 
souscategorie_5 TEXT, 
souscategorie_6 TEXT, 
souscategorie_7 TEXT, 
souscategorie_8 TEXT, 
souscategorie_9 TEXT,
categorie_b TEXT,
partie_2 TEXT, 
categorie_c TEXT, 
souscategorie_10 TEXT, 
souscategorie_11 TEXT, 
souscategorie_12 TEXT, 
souscategorie_13 TEXT, 
souscategorie_14 TEXT, 
categorie_d TEXT, 
conclusion TEXT
);

UPDATE chapitre_13 SET id_cha13= '13';

CREATE TABLE chapitre_14 (
id_cha14 SERIAL NOT NULL PRIMARY KEY, 
topo_theorique TEXT, 
donnees_cas TEXT, 
reponse_cas_qcm TEXT, 
synthese TEXT, 
avis_expert TEXT, 
avis_expert_rep_q1 TEXT, 
avis_expert_rep_q2 TEXT, 
axes_reflex_rep_q1 TEXT, 
axes_reflex_rep_q2 TEXT, 
axes_reflex_rep_q3 TEXT,
partie_1 TEXT, 
categorie_a TEXT, 
categorie_b TEXT,
partie_2 TEXT, 
categorie_c TEXT, 
categorie_d TEXT, 
conclusion TEXT
);

UPDATE chapitre_14 SET id_cha14= '14';

CREATE TABLE chapitre_15 (
id_cha15 SERIAL NOT NULL PRIMARY KEY, 
topo_theorique TEXT, 
donnees_cas TEXT, 
reponse_cas_qcm TEXT, 
synthese TEXT, 
avis_expert TEXT, 
avis_expert_rep_q1 TEXT, 
avis_expert_rep_q2 TEXT, 
avis_expert_rep_q3 TEXT, 
axes_reflex_rep_q1 TEXT, 
axes_reflex_rep_q2 TEXT,
partie_1 TEXT, 
categorie_a TEXT, 
categorie_b TEXT,
partie_2 TEXT, 
categorie_c TEXT, 
categorie_d TEXT, 
conclusion TEXT
);

UPDATE chapitre_15 SET id_cha15= '15';

CREATE TABLE chapitre_16 (
id_cha16 SERIAL NOT NULL PRIMARY KEY, 
topo_theorique TEXT, 
donnees_cas TEXT, 
reponse_cas_qcm TEXT, 
synthese TEXT, 
avis_expert TEXT, 
avis_expert_rep_q1 TEXT, 
avis_expert_rep_q2 TEXT, 
axes_reflex_rep_q1 TEXT, 
axes_reflex_rep_q2 TEXT,
partie_1 TEXT, 
categorie_a TEXT, 
souscategorie_1 TEXT, 
souscategorie_2 TEXT, 
souscategorie_3 TEXT, 
categorie_b TEXT, 
souscategorie_4 TEXT, 
souscategorie_5 TEXT,
partie_2 TEXT, 
categorie_c TEXT, 
souscategorie_6 TEXT, 
souscategorie_7 TEXT, 
categorie_d TEXT, 
souscategorie_8 TEXT, 
souscategorie_9 TEXT, 
souscategorie_10 TEXT, 
branche_a TEXT, 
branche_b TEXT, 
branche_c TEXT, 
branche_d TEXT, 
branche_e TEXT, 
conclusion TEXT
);

UPDATE chapitre_16 SET id_cha16= '16';

CREATE TABLE chapitre_17 (
id_cha17 SERIAL NOT NULL PRIMARY KEY, 
topo_theorique TEXT, 
donnees_cas TEXT, 
reponse_cas_qcm TEXT, 
synthese TEXT, 
avis_expert TEXT, 
avis_expert_rep_q1 TEXT, 
axes_reflex_rep_q1 TEXT, 
axes_reflex_rep_q2 TEXT, 
axes_reflex_rep_q3 TEXT,
partie_1 TEXT, 
categorie_a TEXT, 
categorie_b TEXT, 
souscategorie_1 TEXT, 
souscategorie_2 TEXT, 
branche_a TEXT, 
branche_b TEXT, 
branche_c TEXT,
partie_2 TEXT, 
categorie_c TEXT, 
souscategorie_3 TEXT, 
souscategorie_4 TEXT, 
souscategorie_5 TEXT, 
categorie_d TEXT, 
souscategorie_6 TEXT, 
souscategorie_7 TEXT, 
conclusion TEXT
);

UPDATE chapitre_17 SET id_cha17= '17';

CREATE TABLE chapitre_18 (
id_cha18 SERIAL NOT NULL PRIMARY KEY, 
topo_theorique TEXT, 
donnees_cas TEXT, 
reponse_cas_qcm TEXT, 
synthese TEXT, 
avis_expert TEXT, 
avis_expert_rep_q1 TEXT, 
avis_expert_rep_q2 TEXT, 
avis_expert_rep_q3 TEXT, 
axes_reflex_rep_q1 TEXT, 
axes_reflex_rep_q2 TEXT, 
partie_1 TEXT, 
categorie_a TEXT, 
categorie_b TEXT,
partie_2 TEXT, 
categorie_c TEXT, 
categorie_d TEXT, 
conclusion TEXT
);

UPDATE chapitre_18 SET id_cha18= '18';

CREATE TABLE chapitre_19 (
id_cha19 SERIAL NOT NULL PRIMARY KEY, 
topo_theorique TEXT, 
donnees_cas TEXT, 
reponse_cas_qcm TEXT, 
synthese TEXT, 
avis_expert TEXT, 
avis_expert_rep_q1 TEXT, 
avis_expert_rep_q2 TEXT, 
axes_reflex_rep_q1 TEXT, 
axes_reflex_rep_q2 TEXT,
partie_1 TEXT, 
categorie_a TEXT, 
categorie_b TEXT,
partie_2 TEXT, 
categorie_c TEXT, 
categorie_d TEXT, 
conclusion TEXT
);

UPDATE chapitre_19 SET id_cha19= '19';

CREATE TABLE chapitre_20 (
id_cha20 SERIAL NOT NULL PRIMARY KEY, 
topo_theorique TEXT, 
donnees_cas TEXT, 
reponse_cas_qcm TEXT, 
synthese TEXT, 
avis_expert TEXT, 
avis_expert_rep_q1 TEXT, 
avis_expert_rep_q2 TEXT, 
axes_reflex_rep_q1 TEXT, 
axes_reflex_rep_q2 TEXT, 
axes_reflex_rep_q3 TEXT,
partie_1 TEXT, 
categorie_a TEXT, 
categorie_b TEXT, 
souscategorie_1 TEXT, 
souscategorie_2 TEXT, 
branche_a TEXT, 
branche_b TEXT,
partie_2 TEXT, 
categorie_c TEXT, 
categorie_d TEXT, 
souscategorie_3 TEXT, 
souscategorie_4 TEXT, 
souscategorie_5 TEXT, 
categorie_e TEXT,
partie_3 TEXT, 
souscategorie_6 TEXT, 
souscategorie_7 TEXT, 
categorie_f TEXT, 
categorie_g TEXT, 
conclusion TEXT
);

UPDATE chapitre_20 SET id_cha20= '20';